from bibgrafo.grafo_lista_adjacencia import GrafoListaAdjacencia
from meu_grafo import *

paraiba = MeuGrafo()

paraiba.adicionaVertice('C')
paraiba.adicionaVertice('E')
paraiba.adicionaVertice('P')
paraiba.adicionaVertice('T')
paraiba.adicionaVertice('M')
paraiba.adicionaVertice('Z')
paraiba.adicionaVertice('J')

paraiba.adicionaAresta('a1', 'J', 'C')
paraiba.adicionaAresta('a2', 'C', 'E')
paraiba.adicionaAresta('a3', 'C', 'E')
paraiba.adicionaAresta('a4', 'P', 'C')
paraiba.adicionaAresta('a5', 'P', 'C')
paraiba.adicionaAresta('a6', 'T', 'C')
paraiba.adicionaAresta('a7', 'M', 'C')
paraiba.adicionaAresta('a8', 'M', 'T')
paraiba.adicionaAresta('a9', 'T', 'Z')

paraiba2 = MeuGrafo()

paraiba2.adicionaVertice('C')
paraiba2.adicionaVertice('E')
paraiba2.adicionaVertice('P')
paraiba2.adicionaVertice('T')
paraiba2.adicionaVertice('M')
paraiba2.adicionaVertice('Z')
paraiba2.adicionaVertice('J')
paraiba2.adicionaVertice('W')

paraiba2.adicionaAresta('a1', 'J', 'C')
paraiba2.adicionaAresta('a2', 'C', 'E')
paraiba2.adicionaAresta('a3', 'C', 'E')
paraiba2.adicionaAresta('a4', 'P', 'C')
paraiba2.adicionaAresta('a5', 'P', 'C')
paraiba2.adicionaAresta('a6', 'T', 'C')
paraiba2.adicionaAresta('a7', 'M', 'C')
paraiba2.adicionaAresta('a8', 'M', 'T')
paraiba2.adicionaAresta('a9', 'T', 'Z')

g_c = MeuGrafo(['C', 'J', 'E', 'P', 'A', 'B']) #Grafo desconexo
g_c.adicionaAresta('a1', 'J', 'C')
g_c.adicionaAresta('a2', 'J', 'E')
g_c.adicionaAresta('a3', 'J', 'P')
g_c.adicionaAresta('a4', 'E', 'C')
g_c.adicionaAresta('a5', 'P', 'C')
g_c.adicionaAresta('a6', 'P', 'E')
g_c.adicionaAresta('a7', 'A', 'B')

g_t = MeuGrafo(['A', 'B', 'C', 'D', 'E']) #grafo sem ciclo
g_t.adicionaAresta('a1', 'A', 'B')
g_t.adicionaAresta('a2', 'A', 'C')
g_t.adicionaAresta('a3', 'B', 'D')
g_t.adicionaAresta('a4', 'C', 'E')

grafo_peso = MeuGrafo(['A', 'B', 'C', 'D', 'E', 'F'])
grafo_peso.adicionaAresta('a1', 'A', 'B', 1)
grafo_peso.adicionaAresta('a2', 'A', 'E', 3)
grafo_peso.adicionaAresta('a3', 'B', 'D', 1)
grafo_peso.adicionaAresta('a4', 'B', 'C', 2)
grafo_peso.adicionaAresta('a5', 'C', 'D', 1)
grafo_peso.adicionaAresta('a6', 'E', 'C', 1)
grafo_peso.adicionaAresta('a7', 'E', 'F', 3)
grafo_peso.adicionaAresta('a8', 'B', 'E', 1)
grafo_peso.adicionaAresta('a9', 'C', 'F', 2)

grafo_prim = MeuGrafo(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'])
grafo_prim.adicionaAresta('a1', 'a', 'b', 9)
grafo_prim.adicionaAresta('a2', 'a', 'g', 4)
grafo_prim.adicionaAresta('a3', 'b', 'g', 10)
grafo_prim.adicionaAresta('a4', 'b', 'h', 7)
grafo_prim.adicionaAresta('a5', 'c', 'b', 6)
grafo_prim.adicionaAresta('a6', 'g', 'f', 1)
grafo_prim.adicionaAresta('a7', 'f', 'h', 2)
grafo_prim.adicionaAresta('a8', 'f', 'c', 8)
grafo_prim.adicionaAresta('a9', 'c', 'e', 12)
grafo_prim.adicionaAresta('a10', 'c', 'd', 8)
grafo_prim.adicionaAresta('a11', 'd', 'e', 14)
grafo_prim.adicionaAresta('a12', 'e', 'f', 2)

